### ISSUE TITLE
Changes in Profile are not getting reflected

### ISSUE THREAD

**Issue by ShubhamOjha** [Xe/praise-me#5]
If there are changes in the profile from the last generation, those were not considered while generating the new content generation. 

Are we caching the results?

**Comment by rhaeguard** [comment]
> Are we caching the results?

Yes, the results are cached, see [here](https://github.com/Xe/praise-me/blob/main/routes/api/praise/%5Bname%5D.ts#L92-L95)

You can delete the cached results: https://praise-me.fly.dev/delete

**Comment by Xe** [comment]
The cache is all kinds of fucked ATM because there's 5 cache epochs and not a clear way to tell which one you're getting data from. I didn't expect this to be this popular. These experiments usually have double digit numbers of requests per day. This one had triple digit numbers of requests per hour. I'll figure out a way to reconcile this later when I land in MSP and get to my hotel.

**Comment by Xe** [comment]
Should be fine now
